### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by deku-m** [coloHsq/aggregatron#1]
Hi,

I was trying the plugin but as soon as it is installed. The plugin didnt work for me.
Am i doing something wrong?

Installation:
local_requirements.txt
added git+https://github.com/coloHsq/aggregatron

configuration.py:
PLUGINS:
    'aggregatron',

PLUGINS_CONFIG:
    'aggregatron': {},

ERROR:
<img width="848" alt="Scherm­afbeelding 2024-02-24 om 21 38 40" src="https://github.com/coloHsq/aggregatron/assets/37069737/64ec857e-e8fa-4586-a060-090dcc105658">

**Comment by coloHsq** [comment]
Mmm that's weird, it seems that the template page for rack ports overviews can't be found.
On which version of Netbox are you ?
This error appears when you open Netbox in general or only when you try to go on the plugin?
If it's the second case, does this happens even for devices view ?

**Comment by deku-m** [comment]
> Mmm that's weird, it seems that the template page for rack ports overviews can't be found. On which version of Netbox are you ? This error appears when you open Netbox in general or only when you try to go on the plugin? If it's the second case, does this happens even for devices view ?

Netbox 3.7.3, yes its on both pages and only when going to plugins and use aggregatron.
Used upgrade.sh after adding plugin to the config and requirement  file

**Comment by coloHsq** [comment]
That's even weirder, that's the same version I'm on. I've tried installing this plugin directly from GitHub for testing and everything went fine.
I guess we've run in a "works on my machine" issue.
The only environment in which I've run this plugin is my MacBook and an Alma Linux VM.
In which environment are you running ?

**Comment by deku-m** [comment]
> That's even weirder, that's the same version I'm on. I've tried installing this plugin directly from GitHub for testing and everything went fine. I guess we've run in a "works on my machine" issue. The only environment in which I've run this plugin is my MacBook and an Alma Linux VM. In which environment are you running ?

Indeed very weird but i am running it on Ubuntu 22.04 in proxmox container. 
Installed other plugin and that runs after ./upgrade 
Looks like the templates dont get installed/copied

**Comment by coloHsq** [comment]
Sorry for the dumb question but have you checked if the template files are there ?
There's no reason in my mind on why this shouldn't work.

**Comment by deku-m** [comment]
Well cant find them indeed they are not being copied somehow.
(venv) root@ubuntu:/opt/netbox/venv/lib/python3.10/site-packages/aggregatron# ls
__init__.py  __pycache__  choices.py  filtersets.py  forms.py  migrations  navigation.py  tables.py  urls.py  views.py

Tested to create templates folder with content myself.
No error anymore.

(venv) root@ubuntu:/opt/netbox/netbox# python3 manage.py migrate
Operations to perform:
  Apply all migrations: account, admin, auth, circuits, contenttypes, core, dcim, django_rq, extras, ipam, netbox_cert_plugin, netbox_device_view, netbox_docker_plugin, netbox_documents, netbox_floorplan, netbox_napalm_plugin, netbox_topology_views, sessions, social_django, taggit, tenancy, users, virtualization, vpn, wireless

Missing aggregatron in it, could that be a issue.?

**Comment by coloHsq** [comment]
I dont think so, migrations are usually for database changes. 
This plugin doesn't define any model, so no migrations are required.
Anyway, I've tried to download this repo in all the ways I've come up with, and in every case, the template folder is there.
Which method have you used to get the files ?

**Comment by deku-m** [comment]
Using the following in my local_requirements.txt.
I added:
- git+https://github.com/coloHsq/aggregatron

**Comment by coloHsq** [comment]
I completely missed that method, and in fact, in this case, the template folder did't get downloaded.  
Adding the manifest file seems to solve the issue.  
Try re running upgrade.sh and let me know if it works.

**Comment by deku-m** [comment]
That indeed solved the issue thanksss
