### ISSUE TITLE
Prepare a version for NetBox 4.x

### ISSUE THREAD

**Issue by litebito** [coloHsq/aggregatron#2]
Whit the launch of NetBox v4.x, would you consider updating this plugin to be compatible with NetBox v4.x?

**Comment by coloHsq** [comment]
Yes, but I'm not sure when I'll be able to work on it.

**Comment by coloHsq** [comment]
Hi, It's been quite a bit, but I was able to work on this only recently.
The v0.2 release works with Netbox V4.x
